apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: creative-commons
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: creative-commons
    newName: rg.fr-par.scw.cloud/djnd/creative-commons
    newTag: 'latest'