apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: creative-commons
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: creative-commons
    newName: rg.fr-par.scw.cloud/djnd/creative-commons
    newTag: '7b916b30e11ceccc9515f8be9c08eada2db2e14f'
